# DATASOURCE
spring.datasource.url=jdbc:postgresql://postit:aEuv8yuqda0h2ANhbHnXru9rQqn6psV3@dpg-d078l7qli9vc73f2uvh0-a/postit_9qnj
spring.datasource.name=postit_9qnj
spring.datasource.username=postit
spring.datasource.password=aEuv8yuqda0h2ANhbHnXru9rQqn6psV3
spring.jpa.properties.hibernate.show_sql=true

