# DATASOURCE
spring.datasource.url=jdbc:postgresql://dpg-d077jr3uibrs73f83n0g-a.virginia-postgres.render.com/postitdb_gkvh
spring.datasource.name=postitdb_gkvh
spring.datasource.username=postitdb_gkvh_user
spring.datasource.password=nRPn6VMGaWgXcbxAlxr0KzKqe7T4gp4Y
spring.jpa.properties.hibernate.show_sql=true

